# Generated by Django 5.0 on 2023-12-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=250)),
                ("subjects", models.CharField(max_length=250)),
                ("chapters", models.CharField(max_length=250)),
                ("topics", models.CharField(max_length=250)),
                ("contents", models.CharField(max_length=250)),
            ],
        ),
    ]
