# Generated by Django 5.0 on 2023-12-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=250)),
                ("chapters", models.CharField(max_length=250)),
                ("topic", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="UCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=250)),
                ("topics", models.CharField(max_length=250)),
                ("contents", models.CharField(max_length=250)),
            ],
        ),
    ]
