# Generated by Django 5.0 on 2023-12-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_bcourse_ucourses"),
    ]

    operations = [
        migrations.AddField(
            model_name="bcourse",
            name="contents",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
